# 1. Add the ubuntu (with tag 20.04) below
# -------------------------------------------

# -------------------------------------------

# 2. This is given (don't have to do anything here)
# -------------------------------------------
RUN apt-get update && apt-get install -y num-utils
# -------------------------------------------

# 2. Copy the data.csv file into the container,
# as well as the analysis script (my_analysis.sh)
# Doesn't really matter where (as long as you refer to
# it correctly in the ENTRYPOINT, later)
# -------------------------------------------

# -------------------------------------------

# 3. Define an entrypoint running the analysis, containing
# the executable (/bin/bash), the script (my_analysis.sh) and
# the data (data.csv, as a argument to my_analysis.sh)
# -------------------------------------------

# --------------------------------------------

# No need for a CMD command, here!